version: '3.7'

services:
  minio1:                       # rename on different nodes
    hostname: minio1            # rename on different nodes
    container_name: minio1
    image: minio/minio
    command: server --console-address ":9001" http://minio{1...3}/data{1...2}
    ports:
      - "9000:9000"
      - "9001:9001"
    extra_hosts:
      - "minio1:172.29.0.1"  # 1st node
      - "minio2:172.30.0.1"  # 2nd node
      - "minio3:172.31.0.1"
      - "minio4:192.168.16.1" 
    networks:
      - minio1
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio1233333
    volumes:
      - /home/burak/minio/minio1/data1:/data1          # rename on different nodes
      - /home/burak/minio/minio1/data2:/data2        # rename on different nodes
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
networks:
  minio1:
    external:
      name: minio1